// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rotwdjbpstekitfwkdqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvdHdkamJwc3Rla2l0ZndrZHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDM1MTksImV4cCI6MjA3MTM3OTUxOX0.kQEU2za_5WfJ3knBMSaSwEtHwLOq_Gh-P9qjTUDnhw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});